require 'pry'
require 'nokogiri'
require 'open-uri'
require 'colorize'
require 'mechanize'

require_relative '../lib/nytimes/scraper'
require_relative '../lib/nytimes/book'
require_relative '../lib/nytimes/cli'
require_relative '../lib/nytimes/genre'
