require 'pry'
require 'nokogiri'
require 'open-uri'
require 'colorize'
require 'rubygems'

require_relative '../lib/nytimes/scraper'
require_relative '../lib/nytimes/book'
require_relative '../lib/nytimes/cli'
require_relative '../lib/nytimes/genre'
require_relative '../lib/nytimes/other_genres'
require_relative '../lib/nytimes/other_books'